name: "Zeronet conservacy"
description: "0net para Home Assistant"
version: "0.36"
slug: "zeronet_conservacy_ha"
init: false
arch:
  - armv7
  - aarch64
  - amd64
ports:
  26552/tcp: 26552
  43110/tcp: 43110
options:
  ENABLE_TOR: "disable"
  TOR_CONTROL_PORT: "9151"
  TOR_SOCKS_PORT: "9150"
  TOR_CONTROL_PASSWD: "changeme"
schema:
  ENABLE_TOR: "str"
  TOR_CONTROL_PORT: "str"
  TOR_SOCKS_PORT: "str"
  TOR_CONTROL_PASSWD: "str"
