name: "AceStream Engine ARM"
description: "AceStream Engine para dispositivos ARM en Home Assistant"
version: "1.0.41"
slug: "acestream_engine_arm"
init: false
arch:
  - armv7
  - aarch64
ports:
  6878/tcp: 6878
  8621/tcp: 8621
options:
  EXTRA_ARGUMENTS: "--bind-all --allow-remote=1 --allow-remote-access=1"
schema:
  EXTRA_ARGUMENTS: "str"
