name: "Zeronet"
description: "Zeronet para Home Assistant"
version: "0.9"
slug: "zeronet_ha"
init: false
arch:
  - armv7
  - aarch64
  - amd64
ports:
  26552/tcp: 26552
  43110/tcp: 43110
options:
  ENABLE_TOR: "true"
  UI_PASSWORD: ""
schema:
  ENABLE_TOR: "str"
  UI_PASSWORD: "str"
