name: "AceStream Web Player"
description: "AceStream Web Player en Home Assistant"
version: "0.49"
slug: "acewebplayer"
init: false
arch:
  - armv7
  - aarch64
  - amd64
map:
  - type: share
    read_only: False
ports:
  5000/tcp: 5000
options:
  UI_USERNAME: "user"
  UI_PASSWORD: "user"
  ACESTREAM_PORT: "6878"
  SLUG_ZERONET: ""
schema:
  UI_USERNAME: "str"
  UI_PASSWORD: "str"
  ACESTREAM_PORT: "str"
  SLUG_ZERONET: "str"
