name: "AceStream Web Player"
description: "AceStream Web Player en Home Assistant"
version: "1.08"
slug: "acewebplayer"
init: false
arch:
  - armv7
  - aarch64
  - amd64
map:
  - type: share
    read_only: False
ports:
  5000/tcp: 5000
options:
  UI_USERNAME: "user"
  UI_PASSWORD: "user"
schema:
  UI_USERNAME: "str"
  UI_PASSWORD: "str"
